ALTER TABLE `#__stations_destinations` CHANGE `frn_id` `frn_id` INT(5) NULL DEFAULT NULL,
CHANGE `checked_out_time` `checked_out_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
CHANGE `checked_out` `checked_out` DEFAULT NULL DEFAULT 0,
CHANGE `name` `name` VARCHAR(100)  NOT NULL DEFAULT '',
CHANGE `alias` `alias` VARCHAR(180)  NOT NULL DEFAULT '',
CHANGE `address` `address` VARCHAR(200)  NOT NULL DEFAULT '',
CHANGE `zipcode` `zipcode` VARCHAR(50)  NOT NULL DEFAULT '',
CHANGE `town` `town` VARCHAR(250)  NOT NULL DEFAULT '',
CHANGE `www` `www` VARCHAR(100)  NOT NULL DEFAULT '',
CHANGE `livestream` `livestream` VARCHAR(100)  NOT NULL DEFAULT '',
CHANGE `lat` `lat` VARCHAR(200)  NOT NULL DEFAULT '',
CHANGE `long` `long` VARCHAR(200)  NOT NULL DEFAULT '',
CHANGE `txt` `txt` TEXT  NOT NULL DEFAULT '',
CHANGE `country` `country` INT(11) NOT NULL DEFAULT '33',
CHANGE `access` `access` INT(11) NOT NULL DEFAULT 0;
CHANGE `language` `language` VARCHAR(7)  NOT NULL DEFAULT '',
CHANGE `created` `created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
CHANGE `modified` `modified` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
CHANGE `modified_by` `modified_by` INT(11) NOT NULL DEFAULT 0;
